apiVersion: batch/v1
kind: Job
metadata:
  name: copy-content
spec:
  template:
    spec:
      containers:
      - name: writer
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - echo "<h1>Hello from NFS!</h1>" > /mnt/index.html; sleep 5;
        volumeMounts:
          - name: web-content
            mountPath: /mnt
      restartPolicy: Never
      volumes:
        - name: web-content
          persistentVolumeClaim:
            claimName: web-pvc

